### ISSUE TITLE
How to handle multiple returned random variables

### ISSUE THREAD

**Issue by ibab** [ibab/tensorprob#10]
It would be nice if we could have distributions that return multiple random variables, as in
```python
X, Y = MyFancyDist(a, b, c)
```
This is unfortunately incompatible with `MyFancyDist` being a class.
To support this, we could switch to distributions being implemented as functions.
We could build some machinery (e.g. using decorators) to make it simple to define distributions.

**Comment by chrisburr** [comment]
Superseded by #16
