### ISSUE TITLE
Allow distributions to return several random variables

### ISSUE THREAD

**Issue by ibab** [ibab/tensorprob#16]
Right now distributions can only return a single random variable, because we're using classes to implement them.
It would be nice if we could do things like
```python
X, Y = MyDistribution()
```
For that, we could move away from classes and do something like
```python
@Distribution
def Normal(mu, sigma):
    X = make_placeholder()
    logp = ...
    Distribution.register([X], logp)
    return X
```

**Comment by chrisburr** [comment]
Supersedes #10

**Comment by ibab** [comment]
The interface for that now exists, but we haven't actually implemented the necessary logic in the `Distribution` decorator.

**Comment by chrisburr** [comment]
This should have been added but it's currently untested, see #51.
