### ISSUE TITLE
Implement generic optimiser interface

### ISSUE THREAD

**Issue by chrisburr** [ibab/tensorprob#20]
If possible we should find a way of subclassing [`tensorflow.train.Optimizer`](https://www.tensorflow.org/versions/r0.7/api_docs/python/train.html#Optimizer) to impliment the minimisers in `iminuit` and `scipy`.

Extra points for naming it optimi**_s_**er and minimi**_s_**e!

**Comment by ibab** [comment]
This has been fixed in #25.
