### ISSUE TITLE
Add Minuit as a minimizer

### ISSUE THREAD

**Issue by ibab** [ibab/tensorprob#47]

**Comment by ibab** [comment]
Would be great if we can get https://github.com/iminuit/iminuit/pull/182 merged for this

**Comment by chrisburr** [comment]
I was hoping to use this to make some comparisons using this for the documentation so perhaps we can implement it before iminuit/iminuit#182 is merged?

**Comment by ibab** [comment]
Okay, but we'll run the danger of comparing apples to oranges (e.g. when the finite difference method in Minuit is more advanced than the one in the LBFGS-B implementation).

For a comparison, we should also make sure that the output of one method is as accurate as that of the other. For example, we can subtract the method's results from the analytical solution and compare the histograms. This can easily be done for a simple normal distribution, where the analytical solutions are the `mean` and `std` of the dataset.

**Comment by chrisburr** [comment]
I mean for comparing the difference made by providing gradients to minuit for the `iminuit` documentation.

**Comment by ibab** [comment]
Ah, of course! I thought you meant our documentation.
I can implement this later today based on some code I already have.
I'll try to move as much code as I makes sense out of the scipy optimizer and into the `BaseOptimizer`.
